runtime: python39  # Use the Python 3.9 runtime, but you can choose a different version.

instance_class: F2  # Use the F2 instance class, but you can choose a different class based on your needs.

entrypoint: gunicorn -b :$PORT BertBar:app  # Use Gunicorn as the WSGI server. Adjust "yourapp" to the actual name of your Flask app.

automatic_scaling:
  target_cpu_utilization: 0.65  # Adjust the target CPU utilization based on your app's requirements.

env_variables:
  FLASK_ENV: "production"  # Set Flask environment to production.

handlers:
- url: /.*
  script: auto
